name: "Dependant Jobs"

on: ['push']

jobs:
  igor-secret-example:
    runs-on: ubuntu-latest
    steps:
      - name: Access a secret
        run: | 
          echo "${{ secrets.SECRET_NAME }}" > token.txt
          echo "cat token.txt"
