name: "Dependant Jobs"

on: ['push']

jobs:
  igor-secret-example:
    runs-on: ubuntu-latest
    steps:
      - name: Access a var
        run: | 
          echo "${{ vars.VAR_TEST }}" > token.txt
          cat token.txt
