name: "Dependant Jobs"

on: ['push']

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: second step
        run: echo "World"

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello"


