name: Show Context Demo

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      MY_ENV: production
    steps:
      - name: Show repository and branch
        run: echo "Running in ${{ github.repository }} on branch ${{ github.ref }}"

      - name: Show environment variable
        run: echo "Environment is ${{ env.MY_ENV }}"

      - name: Check if secret is present
        run: |
          if [ -z "${{ secrets.MY_SECRET }}" ]; then
            echo "Secret is missing!"
          else
            echo "Secret is present."
          fi
