name: Show Context Demo

on:
  workflow_dispatch:  # Manual trigger (you click "Run workflow" in the UI)

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      MY_ENV: production
    steps:
      - name: Show repository and branch
        run: echo "Running in ${{ github.repository }} on branch ${{ github.ref }}"

      - name: Show environment variable
        run: echo "Environment is ${{ env.MY_ENV }}"

      - name: Show secret
        run: echo "This is a secret: ${{ secrets.MY_SECRET }}"